[package]
name = "Tieney"
version = "0.1.0"
edition = "2021"

[dependencies]
specs = { version = "0.16.1" }
specs-derive = { version = "0.4.1" }
vector2d = { version = "*" }
rand = { version = "*" }

[dependencies.sdl2]
version = "0.32.1"
features = ["image", "ttf"]
